version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=culinary_recipes_mysql
      - MYSQL_USER=master
      - MYSQL_PASSWORD=pass
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped